version: '3.5'

services:
  postgres:
    container_name: txdemo-db
    image: postgres:15.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:15432:5432"
    restart: unless-stopped

volumes:
  dbdata:
    driver: local