spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true

app:
  scheduling:
    enabled: false #disable scheduling while executing tests
  external:
    exchangerate:
      key: ${EXCHANGERATE_KEY:notprovided}
