server:
  port: 8080
  servlet:
    context-path: /

spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate



management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include:
          - health
          - info

springdoc:
  packagesToScan:
    - lv.gstg.javademo.transactions
  pathsToMatch: /**
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html


# Transactions Demo application
app:
  currencies: USD,EUR,GBP,JPY,CHF,CAD,MXN,PLN,SEK,NOK,RON,CZK,DKK
  external:
    exchangerate: # https://exchangerate.host/documentation
      baseUrl: http://api.exchangerate.host
      key: ${EXCHANGERATE_KEY}
      sources: USD # comma-separated list of currencies for 'source' query param, like GET /live?...&source=USD
      currencies: ${app.currencies}
  scheduling:
    enabled: true