spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
