server:
  port: 8080
  servlet:
    context-path: /

spring:
  flyway:
    enabled: true

management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include:
          - health
          - info

springdoc:
  packagesToScan:
    - lv.gstg.javademo.transactions
  pathsToMatch: /**
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html


# Transactions Demo application
app:
  currencies: USD,EUR,GBP,JPY,CHF,CAD,MXN,PLN,SEK,NOK,RON,CZK,DKK
  external:
    exchangerate: # https://exchangerate.host/documentation
      url: http://api.exchangerate.host
      key: ${EXCHANGERATE_KEY}
      source: USD #source currency to load from exchangerate
      currencies: USD,EUR,GBP,JPY,CHF,CAD,MXN,PLN,SEK,NOK,RON,CZK,DKK

